sonar.projectKey=ekacheri-frontend
sonar.projectName=EKacheri Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=2026sqp_b4359775e5262168ad4b140e5b47a640bb407463